<?php
/**
 * @file
 * Meteologic Mesowest module.
 */

/**
 * Implements hook_meteologic_provider_info();
 */
function meteologic_mesowest_meteologic_provider_info() {
  return array(
    'mesowest' => array(
      'name' => t('Mesowest'),
      'settings' => 'meteologic_mesowest_settings_form',
      // @TODO other stuff
    ),
  );
}

/**
 * Form callback.
 * Display settings form for Meteologic Mesowest.
 */
function meteologic_mesowest_settings_form() {
  $form = array();

  // @TODO insert options here.

  return system_settings_form($form);
}