<?php
/**
 * @name NOAA Weather 
 * @category weather
 * @copyright 2010 Blue Tent Marketing
 * @author Daniel Bopely <dan@bluetent.com> - Originator of this great module!
 * @author Paul T. Huntsberger <paul@bluetent.com> - Ported and expanded to Drupal 6.
 * @author Daniel Bopely <dan@bluetent.com> - Implemented minor bug fixes
 * @package NOAA Weather
 * @version 1.2-beta
 *
 * The NOAA Weather module for Drupal 6 is a port and re-write of the Drupal 5 module. This module allows the end user to have
 * a set of blocks and an admin user interface for assigning weather station information for current forecasts, extended foredcasts and radar station information.
 * 
 * @todo - this still needs a good audit and code cleanup, and eventually will be able to add multiple stations (perhaps a max limit of 5 individual stations) and
 * perhaps some ctools interface integration.
 * @todo - Add a help section.
 * @todo - Add developer documentation.
 */
/*
//Global Module Definitions.
define('METEOLOGIC_MODULE_PATH', drupal_get_path('module', 'meteologic'));
define('METEOLOGIC_DEFAULT_IMAGE_DIRECTORY', METEOLOGIC_MODULE_PATH .'/images/default');
define('METEOLOGIC_CUSTOM_IMAGE_DIRECTORY', METEOLOGIC_MODULE_PATH .'/images/custom');
define('METEOLOGIC_RADAR_IMAGE_DIRECTORY', file_create_path() .'/meteologic_radar');

//Internal Module Configuration.
define ('METEOLOGIC_CACHE_TIME', 3600);
define ('METEOLOGIC_CURRENT_URL', 'http://www.weather.gov/xml/current_obs/');
define ('METEOLOGIC_FORECAST_URL', 'http://www.weather.gov/forecasts/xml/SOAP_server/ndfdSOAPclientByDay.php');
define ('METEOLOGIC_SOCKET_TIMEOUT_SECONDS', 5);

//End User Configuration.
define ('METEOLOGIC_CURRENT_WEATHER_STATION_DEFAULT', variable_get('meteologic_current_weather_station_default', 'INIT'));
define ('METEOLOGIC_CURRENT_LOCATION_NAME_DEFAULT', variable_get('meteologic_current_location_name_default', NULL));
define ('METEOLOGIC_CURRENT_TEMP_UNIT_DEFAULT', variable_get('meteologic_current_temp_unit_default', 'f'));
define ('METEOLOGIC_FORECAST_LAT_DEFAULT', variable_get('meteologic_forecast_lat_default', '47.53'));  
define ('METEOLOGIC_FORECAST_LON_DEFAULT', variable_get('meteologic_forecast_lon_default', '-122.30'));
define ('METEOLOGIC_FORECAST_DAYS_DEFAULT', variable_get('meteologic_forecast_days_default', 5));
define ('METEOLOGIC_FORECAST_DAYSPAN_DEFAULT', variable_get('meteologic_forecast_dayspan_default', 12));
define ('METEOLOGIC_FORECAST_TEMP_UNIT_DEFAULT', variable_get('meteologic_forecast_temp_unit_default', 'f'));
define ('METEOLOGIC_RADAR_STATION_DEFAULT', variable_get('meteologic_radar_station_default', 'INIT'));
define ('METEOLOGIC_RADAR_PICTURE_WIDTH_DEFAULT', variable_get('meteologic_radar_picture_width_default', 600));
define ('METEOLOGIC_RADAR_PICTURE_HEIGHT_DEFAULT', variable_get('meteologic_radar_picture_height_default', 550));

//mesowest
define ('METEOLOGIC_MESOWEST_STATION_DEFAULT', variable_get('meteologic_mesowest_station_default', 'INIT'));
*/
/**
 * Implementation of hook_init().

function meteologic_init() {
  //Module Include Files when the module initializes.
  //Admin Files
  include_once(METEOLOGIC_MODULE_PATH .'/includes/admin.noaa.inc');
  //Include the various stations here, so we can have ano object to play with
  include_once(METEOLOGIC_MODULE_PATH .'/includes/stations.inc');
  //Include defalt icons array, so we can have multiple arrays here
  include_once(METEOLOGIC_MODULE_PATH .'/includes/icons.inc');
  //Include module functions
  include_once(METEOLOGIC_MODULE_PATH .'/includes/noaa.inc');
  //Include theme files
  include_once(METEOLOGIC_MODULE_PATH .'/theme/theme.noaa.inc');
  //Add in jquery js
  drupal_add_js(METEOLOGIC_MODULE_PATH .'/js/jquery.functions.js' ,'module', 'header' );
  //Add CSS files
  drupal_add_css(METEOLOGIC_MODULE_PATH .'/css/noaa-weather-styles.css', 'module', 'all');
  //Check Install
  if (arg(0) == 'admin') {
    _meteologic_check_install();
  }
} 
*/

/**
 * Implements hook_permission().
 */
function meteologic_permission() {
  return array(
    'administer meteologic' => array(
      'title' => t('Administer Meteologic'),
    ),
  );
}
/**
 * Implementation of hook_menu().
 */
function meteologic_menu(){
	$items['admin/config/content/meteologic'] = array(
    'title' => 'Meteologic settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('meteologic_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer meteologic'),
    'description' => 'Configure RAM MLS settings.',
    'file' => 'meteologic.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  
	$items['admin/config/content/meteologic/configure'] = array(
	  'title' => 'Main Meteologic Configuration',
	  'type' => MENU_DEFAULT_LOCAL_TASK,
	  'weight' => 10,
	);


  return $items;
}

/**
 * Implementation of hook_theme()
 */
function meteologic_theme() {
  //Theme blocks.
  //Foreach block we have set in blocks, theme that block
  $blocks = variable_get('meteologic_blocks', NULL);
  foreach ($blocks as $value) {
		$theme[$value['theme']] = array (
      'path'      => METEOLOGIC_MODULE_PATH,
      'template'  => 'theme/'.str_replace('_','-',$value['theme']),
      'arguments' => array( 'widget' => NULL ),
		);
  }
  //@todo - any other themeing to play with?
  return $theme;
}

/**
 * Implementation of hook_block()
 */
function meteologic_block($op = 'list', $delta = 0, $edit = array()) {
  //Switch through Ops @todo - we need to add in configure options, when we add new blocks @todo - When we move to multiple blocks and options, this makes everything easier. Remember block delta's should remain numeric
  $blocks = variable_get('meteologic_blocks', NULL);
  switch ($op) {
    case 'list':
      $items = array();
      //If we have out list of variables, and they are not NULL then show the blocks
      foreach ($blocks as $key => $value ) {
        $items[$key]['info']  = t('NOAA Weather: @INFO', array('@INFO' => $value['info']));
        $items[$key]['cache'] = BLOCK_NO_CACHE;
      }
      return $items;
    case 'view':
      //Find our block through the delta and theme them accordingly @todo - When we move to a more normalized system, our arrays will populate this info automatically now
      $block['subject'] = $blocks[$delta]['info'];
      $block['content'] = theme($blocks[$delta]['theme']);
      return $block;
  }
}


function meteologic_cron() {
  //Update All Weather.
  _meteologic_update_all_weather();
}
