<?php
/**
 * @file
 * Meteologic Mesowest module.
 */

/**
 * Implements hook_meteologic_provider_info();
 */
function meteologic_mesowest_meteologic_provider_info() {
  return array(
    'mesowest' => array(
      'name' => t('Mesowest'),
      'class' => 'MeteologicMesoWest',
      'settings' => 'meteologic_mesowest_settings_form',
      'feeds' => array(
        'current' => array(
          'path' => 'http://example.com/foo',
        ),
      ),
    ),
  );
}

/**
 * Form callback.
 * Display settings form for Meteologic Mesowest.
 */
function meteologic_mesowest_settings_form() {
  $form = array();

  // @TODO insert options here.

  return system_settings_form($form);
}