<?php
/**
 * @file
 * Meteologic Mesowest module.
 */

/**
 * Implements hook_meteologic_provider_info();
 */
function meteologic_mesowest_meteologic_provider_info() {
  return array(
    'mesowest' => array(
      'name' => t('Mesowest'),
      'settings' => 'meteologic_mesowest_settings_form',
      'feeds' => array(
        'current' => array(
          'path' => 'http://mesowest.utah.edu/cgi-bin/droman/xml_get_monitor_data_dev.cgi?stn=@station&searchtype=mostrecent&currentorpast=current',
          'theme' => 'meteologic_mesowest_current',
        ),
      ),
    ),
  );
}

/**
 * Form callback.
 * Display settings form for Meteologic Mesowest.
 */
function meteologic_mesowest_settings_form() {
  $form = array();

  // @TODO insert options here.

  return system_settings_form($form);
}