<?php
/**
 * @file
 * Meteologic MesoWest theme functions.
 *
 * NOTE: These theme functions *must* live in this file, named exactly like this.
 * We enforce convention over configuration in order to make things simpler
 * for submodules so theme callbacks must always live in "MODULENAME.theme.inc",
 * located in the module's root.
 */

/**
 * Provides a theme for them MesoWest Current Conditions feed.
 */
function theme_meteologic_mesowest_current($variables) {
  $data = $variables['data'];
}