<?php
/**
 * @file
 * Meteologic NOAA module.
 */

/**
 * Implements hook_meteologic_provider_info();
 */
function meteologic_noaa_meteologic_provider_info() {
  return array(
    'noaa' => array(
      'name' => t('NOAA'),
      'class' => 'MeteologicNOAA',
      'settings' => 'meteologic_noaa_settings_form',
      // @TODO other stuff
    ),
  );
}

/**
 * Form callback.
 * Display settings form for Meteologic Mesowest.
 */
function meteologic_noaa_settings_form() {
  $form = array();

  // @TODO insert options here.

  return system_settings_form($form);
}