<?php
/**
 * @file
 * Meteologic NOAA module.
 */

/**
 * Implements hook_meteologic_provider_info();
 */
function meteologic_noaa_meteologic_provider_info() {
  return array(
    'noaa' => array(
      'name' => t('NOAA'),
      'settings' => 'meteologic_noaa_settings_form',
      'feeds' => array(
        'current' => array(
          'path' => 'http://w1.weather.gov/xml/current_obs/@station.xml',
          'tokens' => array('@station'),
          'theme' => 'meteologic_noaa_current',
        ),
        'forecast' => array(
          'path' => 'http://graphical.weather.gov/xml/SOAP_server/ndfdSOAPclientByDay.php?lat=@lat&lon=@lon&format=12+hourly&startDate=&numDays=@days&Submit=Submit',
          'tokens' => array('@lat', '@lon', '@days'),
          'theme' => 'meteologic_noaa_forecast',
        ),
      ),
      'stations' => array(
        'weather' => 'meteologic_noaa_stations_weather',
        'radar' => 'meteologic_noaa_stations_radar',
      ),
    ),
  );
}

/**
 * Returns a list of weather stations for the NOAA provider.
 * This is a wrapper around _meteologic_noaa_stations_weather(), which allows
 * us to lazy-load the extra big file.
 */
function meteologic_noaa_stations_weather() {
  module_load_include('inc', 'meteologic_noaa', 'meteologic_noaa_stations');
  return _meteologic_noaa_stations_weather();
}

/**
 * Returns a list of radar stations for the NOAA provider.
 * This is a wrapper around _meteologic_noaa_stations_radar(), which allows
 * us to lazy-load the extra big file.
 */
function meteologic_noaa_stations_radar() {
  module_load_include('inc', 'meteologic_noaa', 'meteologic_noaa_stations');
  return _meteologic_noaa_stations_radar();
}